### ISSUE TITLE
Hugh's Checklist for Wednesday

### ISSUE THREAD

**Issue by hughsk** [hughsk/mobile-arcade#42]
Just my personal checklist of things I need to do by Wednesday.

* [x] New controller UI

Needs workshop:

* [x] Lasercut remaining pieces
* [x] Glue remaining pieces
* [x] Get SSH-over-USB working on Windows with a static IP (https://www.thepolyglotdeveloper.com/2016/06/connect-raspberry-pi-zero-usb-cable-ssh/)
* [x] Set up Raspberry Pi hotspot (https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md)
* [x] Use nodogsplash to redirect everything to controller IP (https://pimylifeup.com/raspberry-pi-captive-portal/ and http://nodogsplash.readthedocs.io/en/latest/customize.html)

Needs delivery (all due tomorrow, need to pick up after it arrives and before 6pm):

* [ ] Mount the monitor using velcro, wood blocks and glue
* [x] Get HDMI cable
* [x] Test hotspot with game
* [ ] Mount laptop, power board and RPi inside box

If time permits:

* [ ] Paint box with undercoat and then colour layer
* [ ] Add hinges
* [ ] Add handle
* [ ] Add open/close clips
